name:                projects
version:             0.1.0.0

dependencies:
- aeson
- async
- base
- bytestring
- concurrent-output
- directory
- filepath
- http-client
- http-client-tls
- http-types
- network-uri
- process
- unordered-containers

executables:
  projects:
    main:                Project/Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N