name:                projects
version:             0.0.0.0

dependencies:
- aeson
- ansi-terminal
- async
- base
- bytestring
- directory
- filepath
- filelock
- http-client
- http-client-tls
- http-types
- hslogger
- network-uri
- optparse-applicative
- process

executables:
  projects:
    main:                Project/Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
